# Container-based infrastructure has been fully deprecated.
# https://docs.travis-ci.com/user/reference/trusty/#container-based-infrastructure
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gYAzVukFw3ssmQzfovoKTNJnzQbUhF13tksHHhe5dqQWglxdix39wY405nMmzRm/21ZpIq3OFIlI7fnHdZSGkVPS/nPPxbzUkjYUh+zkujYwsqgjZecq9vGaoarnyV9CcI+2D6qUVnArHQ02FKxirtXduGvElZ/eRIa/hBfpgn4="

dist: trusty

language: java
jdk:
# - openjdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

branches:
  only:
    - master

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2

script:
  - ./bin/run_travis_tests.sh

after_success:
  - mvn clean cobertura:cobertura coveralls:report
